### ISSUE TITLE
Plugin disappears after updating

### ISSUE THREAD

**Issue by ralts00** [einancunlu/Flatten-Plugin-for-Sketch#11]
Update the plugin to 1.6 from sketch, and now the plugin disappeared in the list of plugins, and sketch runner appears only version 1.5, and now synonymous sketch runner does not allow me to install it :(

Sketch 45.1

PD. In the finder the plugin appears but sketch no longer recognizes it
![captura de pantalla 2017-07-06 13 01 55](https://user-images.githubusercontent.com/5034252/27925679-4fb082fa-624b-11e7-8bdd-ead15e6ebfef.png)

**Comment by davekover** [comment]
I manually edited the version number within the plugin to 1.6 (after updating to 1.6.1) and it reappears within Sketch. I'm not sure why that worked. ¯\_(ツ)_/¯

**Comment by ralts00** [comment]
Works after manually changing to 1.6 instead of 1.6.1
Thanks @davekover !

**Comment by ralts00** [comment]
Now sketch thinks I still do not have the latest version
![captura de pantalla 2017-07-06 13 19 51](https://user-images.githubusercontent.com/5034252/27926390-e3b61cd8-624d-11e7-8f20-cb3799556571.png)

**Comment by einancunlu** [comment]
I found the problem, it's just a small typo in the version number that causes Sketch to misunderstand it. I fixed, it should work now!
