### ISSUE TITLE
Different versions in sketch runner and sketch app

### ISSUE THREAD

**Issue by ralts00** [einancunlu/Flatten-Plugin-for-Sketch#12]
Sketch runner has a different version of the plugin it seems to be 1.5 but I have 1.6.1

![captura de pantalla 2017-07-06 15 08 02](https://user-images.githubusercontent.com/5034252/27930647-fcfd9d74-625c-11e7-80ba-55bf00cda9a9.png)

**Comment by einancunlu** [comment]
Ahh... I think I fixed it this time, hopefully! : ) But you might need to delete and reinstall it. I think I have caused a weird loop there so it might not update successfully. : )
