### ISSUE TITLE
seems to not work with Sketch 47

### ISSUE THREAD

**Issue by VodafoneCoreApp** [einancunlu/Flatten-Plugin-for-Sketch#13]
Hi there, could you possibly look into and check what exactly is happening? atm the plugin creates the Group with the flattened Image, but it should also at the same time 1. hide the actual layers and 2. paste the bitmap on the “Flattened Image” shape (it stays just empty)

thanks in advance

**Comment by einancunlu** [comment]
Fixed! Please update your plugin. : )
