### ISSUE TITLE
Color hex FDBD10 turned to hex FFF091 after flattern

### ISSUE THREAD

**Issue by matteozambon89** [einancunlu/Flatten-Plugin-for-Sketch#16]
I have a series of objects with a single Fill of hex FDBD10 and any time I try to flattern them I see the color turning whiteish.

Here's an example:

Artboard with a single rectangle filled with hex FDBD10 and all blending Normal:
<img width="214" alt="screen shot 2018-03-10 at 13 57 16" src="https://user-images.githubusercontent.com/2357170/37244691-9c562b40-246b-11e8-8bba-b1fa51eceb32.png">

Artboard before (with unflatten object visible) and after (with flatten object visible)
<img width="736" alt="screen shot 2018-03-10 at 13 58 15" src="https://user-images.githubusercontent.com/2357170/37244675-7051dabc-246b-11e8-919f-09e72a3ff216.png">

<img width="237" alt="screen shot 2018-03-10 at 13 58 10" src="https://user-images.githubusercontent.com/2357170/37244678-79b55264-246b-11e8-99a2-2af4a7cdfd3c.png">

<img width="1440" alt="screen shot 2018-03-10 at 13 59 22" src="https://user-images.githubusercontent.com/2357170/37244683-850c1198-246b-11e8-8934-f07e718c6c0c.png">

**Comment by einancunlu** [comment]
Could you send me an example Sketch file here? I tried to do the same thing and it's working on my computer, maybe I missed something.

**Comment by matteozambon89** [comment]
Hi @einancunlu 
I'm using Sketch 48.2 do you have the same on your side? I can cook a simple file for you.

I tried create a new Sketch file and this issue always appear.

**Comment by einancunlu** [comment]
I'm using version 49. Okay then, I will look at your example file when you put here.

**Comment by matteozambon89** [comment]
Let me try to upgrade Sketch and if it doesn't solve I'll let you know

**Comment by matteo-harpoon** [comment]
Hi @einancunlu 
sorry for the delay I had a project to finish and I couldn't update in the middle.

Here's the test file with the issue even on 49.

Let me know if I'm doing anything wrong 👍 

[flatten-issue.zip](https://github.com/einancunlu/Flatten-Plugin-for-Sketch/files/1808647/flatten-issue.zip)

**Comment by matteozambon89** [comment]
Hi @einancunlu
sorry for the delay I had a project to finish and I couldn't update in the middle.

Here's the test file with the issue even on 49.

Let me know if I'm doing anything wrong 👍

[flatten-issue.zip](https://github.com/einancunlu/Flatten-Plugin-for-Sketch/files/1808652/flatten-issue.zip)

**Comment by matteozambon89** [comment]
I did another test with a different color and it seems to be happening with every color I set.

Sketch Version: 49
Sketch Color Profile: `Unmanaged`
OS: `MacOS 10.13.4`
OS Color Profile: `Color LCD`
Plugin Installed: only Flatten (I removed all the others)

Issue happening on both new and old files.

[flatten-issue-2.zip](https://github.com/einancunlu/Flatten-Plugin-for-Sketch/files/1808704/flatten-issue-2.zip)

**Comment by matteozambon89** [comment]
Hi @einancunlu 

I found the issue is related with High Sierra https://www.sketchapp.com/support/troubleshooting/gamma-fix-high-sierra

We can close this issue as it's not related with this plugin but a bug with Sketch
