### ISSUE TITLE
bug in sketch 50.2

### ISSUE THREAD

**Issue by ralts00** [einancunlu/Flatten-Plugin-for-Sketch#17]
It does not work at all :(
and when I do flatten all back to the first page

**Comment by einancunlu** [comment]
Argh... it gets broken every time Sketch updates. Unfortunately, Sketch plugin API documentation is not completed yet and not enough to find the fix directly. I searched some and couldn't find the solution. I don't have enough time to go more deep for now.

Sorry, but for now I have to depreciate the plugin for sometime until I have time to rewrite everything with the new Javascript API (it depends on when they will update the documentation too). 

You can convert artboards into symbols to replace the plugin's artboard flattening feature (partially). Other than that, if you put background layer into artboards with the same size, layer flattening feature works fine (giving background color to artboards doesn't work anymore).

**Comment by ralts00** [comment]
thank you very much for reviewing the issue so quickly,
I am sad that they do not update the documentation quickly, because I love the plugin.
But while I'm going to follow the steps you tell me, thank you very much friend :)

**Comment by celor** [comment]
Here is a patch that can help you @ralts00 https://github.com/einancunlu/Flatten-Plugin-for-Sketch/pull/18/commits/308035c43c54fe4f5ebc24f041cec4dbc6345080

**Comment by einancunlu** [comment]
That's great, thanks! It fixes one of the problems. But, there is one other problem that I need to fix. Normally I was going to delay it, but maybe I can try to figure it out now. Either way, I will merge your request soon.

**Comment by einancunlu** [comment]
I merged the patch of @celor for temporarily. You can download the plugin and update manually. 

I'm working on a new version of the plugin (Flatten v2.0). I have some ideas to make it more usable and also to expand the functionality. But I don't know when it would finish, it can take time as I'm trying to update all the code with the new Javascript API. : )

**Comment by ralts00** [comment]
Thank you very much, I will update manually as you indicate, and I will look forward to the new version with great joy :)

**Comment by einancunlu** [comment]
Hey guys, good news! I have re-coded the plugin from ground-up and added some new features. I'm working on a Medium post about the v.2.0 details and I will publish it on Product Hunt later. So, until it's official, you can use the version attached. I would appreciate it if you report any bugs or give some feedback.

New features:
- Auto flattening: If you select "Flattened Image" layers in groups or artboards, they will be updated automatically.
- Auto toggling: Select the hidden actual layer to make it visible automatically. You can select back the flattened image to toggle back and update.
- Unflattening: Select a flattened group and apply to revert it back. If you select artboard image layer, it just edits the name.
- Settings panel for customization the values like flattening scale (quality) and layer names. You can also turn off or turn on the automated features there.
- Customized flattening scale (quality) for layers that contain #s[scale value] tag in their name. For example if a layer has #s2 tag in its name, it will be flattened in double quality. (Range is from 0.02 to 10)
- No need for adding artboard color anymore.

There are some other small things I didn't mention here, I will write all of them in the article. Hope you like it! : )

[Flatten.sketchplugin.zip](https://github.com/einancunlu/Flatten-Plugin-for-Sketch/files/2073616/Flatten.sketchplugin.zip)

**Comment by einancunlu** [comment]
Hey guys, you can download the newer version. I did some bug fixes and added new features. See the Medium post for all the details: https://medium.com/@einancunlu/flatten-2-0-sketch-plugin-f53984696990
