### ISSUE TITLE
Problems in Sketch Beta 39

### ISSUE THREAD

**Issue by rohapa** [einancunlu/Flatten-Plugin-for-Sketch#2]
After using Flatten, the Reload button doesn't appear, and the shared style is blank.

**Comment by einancunlu** [comment]
What is your Sketch version and could you send an example Sketch file after doing that please. I have tested the update in the latest version and it works without problems here.

**Comment by einancunlu** [comment]
It's normal that reload button doesn't appear because I call it automatically now.

**Comment by rohapa** [comment]
Version 39 (31667)
https://www.dropbox.com/s/vjvm27v0iz9910k/test.sketch?dl=0

**Comment by einancunlu** [comment]
I detected something that wasn't causing error before, and fixed it. Download and try the new version now and let me know if there is any other problem.

**Comment by rohapa** [comment]
WORKS LIKE A CHARM!
BEST PLUGIN FOR SKETCH!

**Comment by rohapa** [comment]
Thanks! You are the greatest!

**Comment by einancunlu** [comment]
Thanks, happy to hear!
