### ISSUE TITLE
String “Flatten” already taken by Sketch

### ISSUE THREAD

**Issue by illustree** [einancunlu/Flatten-Plugin-for-Sketch#3]
Hi, atm the command “Flatten” is used by Sketch: Layer / Paths / Flatten ... probably you could change your “Flatten” to something else (e.g. “Flatten selected”) so that it would be possible to set a shortkey in Mac Settings? thanks!

**Comment by einancunlu** [comment]
Hi, I updated the name, you can download the new version. : )

**Comment by illustree** [comment]
great! thanks ... starting power-use your awesome plugin ;----)
